spring:
  datasource:
    url: jdbc:sqlserver://travelagency.database.windows.net:1433;databaseName=Travel_Agency_DB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sqladmin
    password: qazWSX123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2016Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081/realms/Travel-Agency

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-demo
      client-secret: KHOniqycsZ2UYPDtxU3pXIMlfFwT5QtM

server:
  port: 8080