spring:
  datasource:
    url: jdbc:sqlserver://travelagency.database.windows.net:1433;databaseName=Travel_Agency_DB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sqladmin
    password: qazWSX123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2016Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081/realms/Travel-Agency

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

paypal:
  mode: sandbox
  client:
    id: ATYCSLqaQaXDjt7LfgXJW6KMwLw49Ly7rfYv3Rfg30XVx9vttad4xnS4xkbk2foomkIM0vKwZHT-wXO5
    secret: ECex0Yg2iaRigZV4jBbCAST5lSBWMwZSJw2YDPJx9UGHvfsECQ5r4PJyVrCA6GZQLKUMHnQOMUSxlpAb

server:
  port: 8080