spring:
  datasource:
    url: change_me
    username: change_me
    password: change_me
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2016Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: change_me

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  ai:
    openai:
      api-key: change_me

paypal:
  mode: sandbox
  client:
    id: change_me
    secret: change_me

server:
  port: 8080
